spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/interior?serverTimezone=Asia/Seoul
    username: interior
    password: interior0428

  security:
    user:
      name: interior
      password: interior0428
