spring:
  profiles:
    active: local
    group:
      local: local, common, secret
      blue: blue, common, secret

server:
  port: 8080
  env: blue

  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
--- ## blue
spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8080
  serverAddress: 13.124.166.1

serverName: blue_server

---
server:
  config:
    activate:
      on-profile: common

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

  config:
    import: application-secret.yml


logging:
  level:
    org:
      springframework:
        security: DEBUG
    rg.hibernate.type: trace